# Automatically updates "vX" branches based on GitHub releases. To cut a new
# release, use the GitHub UI where you enter a tag name and release name of
# "vX.Y.Z". See https://github.com/jupyterhub/action-k3s-helm/releases.
---
name: Release updates

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # Action reference: https://github.com/Actions-R-Us/actions-tagger
      # NOTE: We pin a version not to have the source code (.ts files), but the
      #       compiled source code (.js files). This git hash is what v2.0.1
      #       referenced 30 December 2020.
      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb
        with:
          token: "${{ github.token }}"
